In [2]:
import pandas as pd

In [4]:
df=pd.read_csv('preterm-and-very-preterm-births-by-race-ethnicity.csv')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 162 entries, 0 to 161
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Year            162 non-null    int64
 1   Race/Ethnicity  162 non-null    object
 2   Birth Type      162 non-null    object
 3   Total Births    162 non-null    int64
 4   Events          162 non-null    int64
 5   Percent         162 non-null    float64
 6   Upper 95% CI    162 non-null    float64
 7   Lower 95% CI    162 non-null    float64
dtypes: float64(3), int64(3), object(2)
memory usage: 10.3+ KB

In [6]:
df.head(10)

,Year,Race/Ethnicity,Birth Type,Total Births,Events,Percent,Upper 95% CI,Lower 95% CI
0,2010,African-American,Preterm Births,27634,3441,12.5,12.8,12.1
1,2010,African-American,Very Preterm Births,27634,731,2.6,2.8,2.5
2,2011,African-American,Preterm Births,26991,3241,12.0,12.4,11.6
3,2011,African-American,Very Preterm Births,26991,729,2.7,2.9,2.5
4,2012,African-American,Preterm Births,26446,3226,12.2,12.6,11.8
5,2012,African-American,Very Preterm Births,26446,748,2.8,3.0,2.6
6,2013,African-American,Preterm Births,25790,3075,11.9,12.3,11.5
7,2013,African-American,Very Preterm Births,25790,692,2.7,2.9,2.5
8,2010,American Indian,Preterm Births,1900,191,10.1,11.5,8.8
9,2010,American Indian,Very Preterm Births,1900,21,1.1,1.7,0.7

In [7]:
dff=pd.read_csv('preterm-and-very-preterm-births-by-county.csv')

In [8]:
dff.head(10)

,Year,County,Birth Type,Total Births,Events,Percent,Lower 95% CI,Upper 95% CI
0,2010,Mariposa,Preterm Births,145,NaN,NaN,NaN,NaN
1,2012,Tehama,Very Preterm Births,767,NaN,NaN,NaN,NaN
2,2013,Glenn,Very Preterm Births,398,NaN,NaN,NaN,NaN
3,2013,Mendocino,Very Preterm Births,1005,NaN,NaN,NaN,NaN
4,2013,Mono,Preterm Births,150,NaN,NaN,NaN,NaN
5,2013,Yuba,Very Preterm Births,1199,NaN,NaN,NaN,NaN
6,2014,Calaveras,Very Preterm Births,347,NaN,NaN,NaN,NaN
7,2015,Tehama,Very Preterm Births,828,NaN,NaN,NaN,NaN
8,2018,Nevada,Very Preterm Births,770,NaN,NaN,NaN,NaN
9,2010,Mono,Preterm Births,151,11.0,7.3,4.1,12.6